### ISSUE TITLE
Issue loading a password file, when selecting pre-compromise option 2 - Brute force credentials

### ISSUE THREAD

**Issue by m4nbat** [vectra-ai-research/MAAD-AF#3]
Hi I am receiving an issue when Issue where the password file does not seem to be picked up when selecting pre-compromise option 2 - Brute force credentials.

Hopefully I'm not being dull but here are the screenshots:

![image](https://user-images.githubusercontent.com/16122365/225627476-bcd81a5c-7517-4fcc-890b-26e38be81f42.png)

File exists in the path I launched PowerShell from which was the same directory as the MAAD_Attack.ps1:

![image](https://user-images.githubusercontent.com/16122365/225627680-039e8998-eb2b-4a27-9d5b-c17e7c830f89.png)

Thanks for producing the tool 👍

**Comment by openrec0n** [comment]
Thanks for reporting this. The latest version of MAAD-AF adds more input checks and files preview that should help address this issue. 
If the issue persists, do let us know and consider sharing details around OS & PS version you are using?

Thanks!

**Comment by m4nbat** [comment]
It was an Azure Windows 10 virtual machine 2 weeks old. I will dig out
details for you.

Cheers
