### ISSUE TITLE
Modules can't be installed

### ISSUE THREAD

**Issue by ablito19** [vectra-ai-research/MAAD-AF#6]
I got many error when installing modules.
I try it with PS5 (x86,x64) and PS7 (x86,x64) winth admin but no way to use it.

<img width="641" alt="image" src="https://github.com/vectra-ai-research/MAAD-AF/assets/5755450/a94faf88-02d6-4a87-b34a-99bffa3706ff">

<img width="703" alt="image" src="https://github.com/vectra-ai-research/MAAD-AF/assets/5755450/5d77b22b-d5a3-4008-9634-15ead6530758">

**Comment by openrec0n** [comment]
Thanks for reporting this. The primary issue was that the modules were getting installed but no messages were displayed for them. The latest push update allows MAAD-AF to be more verbose during the module check and installation process. Hopefully this solves your issue.

**Comment by openrec0n** [comment]
PS 5 x64 is best recommended
